export const trnsxnData = [
  {
    name: 'Netflix',
    description: 'Month subscription',
    transactionType: 'Pay',
    amount: 12,
    isAurayaAsset: false,
    date: '01-01-2024',
  },
  {
    name: 'Phone bill',
    description: 'Month subscription',
    transactionType: 'Pay',
    amount: 120,
    isAurayaAsset: false,
    date: '02-01-2024',
  },
  {
    name: 'To Family',
    description: 'Small loan',
    transactionType: 'Send',
    amount: 120,
    isAurayaAsset: false,
    date: '03-01-2024',
  },
  {
    name: 'From Trader',
    description: 'Sold Asset',
    transactionType: 'Sell',
    amount: 120,
    isAurayaAsset: true,
    date: '04-01-2024',
  },
  {
    name: 'With System',
    description: 'Quick Swap',
    transactionType: 'Swap',
    amount: 1200,
    isAurayaAsset: true,
    date: '29-12-2023',
  },
  {
    name: 'Services',
    description: 'Web Development',
    transactionType: 'Receive',
    amount: 12,
    isAurayaAsset: false,
    date: '05-01-2024',
  },
  {
    name: 'Phone bill',
    description: 'Month subscription',
    transactionType: 'Pay',
    amount: 120,
    isAurayaAsset: false,
    date: '02-01-2024',
  },
  {
    name: 'To Family',
    description: 'Small loan',
    transactionType: 'Send',
    amount: 120,
    isAurayaAsset: false,
    date: '03-01-2024',
  },
  {
    name: 'To Trader',
    description: 'Small loan',
    transactionType: 'Sell',
    amount: 120,
    isAurayaAsset: true,
    date: '04-01-2024',
  },
  {
    name: 'To System',
    description: 'Quick Swap',
    transactionType: 'Swap',
    amount: 1200,
    isAurayaAsset: true,
    date: '29-12-2023',
  },
];
